variables:
- group: docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - script: 'sudo docker login $(DOCKER_FQDN) --username $(DOCKER_USERNAME) --password $(DOCKER_PASSWORD)'
- script: echo $DOCKER_FQDN
  env:
    DOCKER_FQDN: $(DOCKER_FQDN)
    
- bash: 'sudo apt-get update && sudo apt-get install qemu-user-static -y'

- bash: 'sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset'

- task: Bash@3
  inputs:
    script: 'sudo $(System.DefaultWorkingDirectory)/.azure/deploy.sh'
    arguments: '$(DOCKER_USERNAME) $(DOCKER_PASSWORD)'
