trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $DOCKER_USERNAME
  env:
    MySecret: $(DOCKER_USERNAME)

- script: echo $DOCKER_PASSWORD
  env:
    MySecret: $(DOCKER_PASSWORD)

- script: |
    docker login $(DOCKER_FQDN) \
    --username $(DOCKER_USERNAME) \
    --password $(DOCKER_PASSWORD)
- script: echo "test ${DOCKER_USERNAME}"

- script: 'sudo apt-get update && sudo apt-get install qemu-user-static -y'

- script: 'sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset'

#- script: 'sudo $(System.DefaultWorkingDirectory)/.azure/test.sh'
